// Mocks generated by Mockito 5.4.5 from annotations
// in articles_st_trial/test/domain/data/article_previews_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:article_browser/data/api/api_client.dart' as _i5;
import 'package:article_browser/data/models/article_data/article_data.dart'
    as _i2;
import 'package:article_browser/data/models/comment_data/comment_data.dart'
    as _i7;
import 'package:article_browser/data/providers/local_storage_provider.dart'
    as _i8;
import 'package:article_browser/data/transformers/article_previews_codec.dart'
    as _i9;
import 'package:article_browser/data/transformers/article_previews_factory.dart'
    as _i11;
import 'package:article_browser/domain/models/article/article.dart' as _i12;
import 'package:article_browser/domain/models/article_previews/article_previews.dart'
    as _i3;
import 'package:article_browser/domain/models/reception_details/reception_details.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleData_0 extends _i1.SmartFake implements _i2.ArticleData {
  _FakeArticleData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArticlePreviews_1 extends _i1.SmartFake
    implements _i3.ArticlePreviews {
  _FakeArticlePreviews_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ArticleDataCopyWith_2<$Res> extends _i1.SmartFake
    implements _i2.$ArticleDataCopyWith<$Res> {
  _Fake$ArticleDataCopyWith_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReceptionDetails_3 extends _i1.SmartFake
    implements _i4.ReceptionDetails {
  _FakeReceptionDetails_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ArticlePreviewsCopyWith_4<$Res> extends _i1.SmartFake
    implements _i3.$ArticlePreviewsCopyWith<$Res> {
  _Fake$ArticlePreviewsCopyWith_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  @override
  _i6.Future<List<_i2.ArticleData>> fetchArticles() =>
      (super.noSuchMethod(
            Invocation.method(#fetchArticles, []),
            returnValue: _i6.Future<List<_i2.ArticleData>>.value(
              <_i2.ArticleData>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i2.ArticleData>>.value(
              <_i2.ArticleData>[],
            ),
          )
          as _i6.Future<List<_i2.ArticleData>>);

  @override
  _i6.Future<_i2.ArticleData> fetchArticleDetails(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchArticleDetails, [id]),
            returnValue: _i6.Future<_i2.ArticleData>.value(
              _FakeArticleData_0(
                this,
                Invocation.method(#fetchArticleDetails, [id]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.ArticleData>.value(
              _FakeArticleData_0(
                this,
                Invocation.method(#fetchArticleDetails, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.ArticleData>);

  @override
  _i6.Future<List<_i7.CommentData>> fetchComments(int? articleId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchComments, [articleId]),
            returnValue: _i6.Future<List<_i7.CommentData>>.value(
              <_i7.CommentData>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i7.CommentData>>.value(
              <_i7.CommentData>[],
            ),
          )
          as _i6.Future<List<_i7.CommentData>>);
}

/// A class which mocks [LocalStorageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageProvider extends _i1.Mock
    implements _i8.LocalStorageProvider {
  @override
  _i6.Future<void> set({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#set, [], {#key: key, #value: value}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeAll() =>
      (super.noSuchMethod(
            Invocation.method(#removeAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ArticlePreviewsCodec].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlePreviewsCodec extends _i1.Mock
    implements _i9.ArticlePreviewsCodec {
  @override
  _i3.ArticlePreviews decodeDetailsFromJson(String? previewsJsonString) =>
      (super.noSuchMethod(
            Invocation.method(#decodeDetailsFromJson, [previewsJsonString]),
            returnValue: _FakeArticlePreviews_1(
              this,
              Invocation.method(#decodeDetailsFromJson, [previewsJsonString]),
            ),
            returnValueForMissingStub: _FakeArticlePreviews_1(
              this,
              Invocation.method(#decodeDetailsFromJson, [previewsJsonString]),
            ),
          )
          as _i3.ArticlePreviews);

  @override
  String encodeToJsonString(_i3.ArticlePreviews? articlePreviews) =>
      (super.noSuchMethod(
            Invocation.method(#encodeToJsonString, [articlePreviews]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#encodeToJsonString, [articlePreviews]),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.method(#encodeToJsonString, [articlePreviews]),
            ),
          )
          as String);
}

/// A class which mocks [ArticlePreviewsFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlePreviewsFactory extends _i1.Mock
    implements _i11.ArticlePreviewsFactory {
  @override
  _i3.ArticlePreviews createNetworkPreviews(
    List<_i2.ArticleData>? articlesData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNetworkPreviews, [articlesData]),
            returnValue: _FakeArticlePreviews_1(
              this,
              Invocation.method(#createNetworkPreviews, [articlesData]),
            ),
            returnValueForMissingStub: _FakeArticlePreviews_1(
              this,
              Invocation.method(#createNetworkPreviews, [articlesData]),
            ),
          )
          as _i3.ArticlePreviews);
}

/// A class which mocks [ArticleData].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleData extends _i1.Mock implements _i2.ArticleData {
  @override
  int get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get body =>
      (super.noSuchMethod(
            Invocation.getter(#body),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#body),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#body),
            ),
          )
          as String);

  @override
  _i2.$ArticleDataCopyWith<_i2.ArticleData> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$ArticleDataCopyWith_2<_i2.ArticleData>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub:
                _Fake$ArticleDataCopyWith_2<_i2.ArticleData>(
                  this,
                  Invocation.getter(#copyWith),
                ),
          )
          as _i2.$ArticleDataCopyWith<_i2.ArticleData>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ArticlePreviews].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlePreviews extends _i1.Mock implements _i3.ArticlePreviews {
  @override
  _i4.ReceptionDetails get receptionDetails =>
      (super.noSuchMethod(
            Invocation.getter(#receptionDetails),
            returnValue: _FakeReceptionDetails_3(
              this,
              Invocation.getter(#receptionDetails),
            ),
            returnValueForMissingStub: _FakeReceptionDetails_3(
              this,
              Invocation.getter(#receptionDetails),
            ),
          )
          as _i4.ReceptionDetails);

  @override
  List<_i12.Article> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <_i12.Article>[],
            returnValueForMissingStub: <_i12.Article>[],
          )
          as List<_i12.Article>);

  @override
  _i3.$ArticlePreviewsCopyWith<_i3.ArticlePreviews> get copyWith =>
      (super.noSuchMethod(
            Invocation.getter(#copyWith),
            returnValue: _Fake$ArticlePreviewsCopyWith_4<_i3.ArticlePreviews>(
              this,
              Invocation.getter(#copyWith),
            ),
            returnValueForMissingStub:
                _Fake$ArticlePreviewsCopyWith_4<_i3.ArticlePreviews>(
                  this,
                  Invocation.getter(#copyWith),
                ),
          )
          as _i3.$ArticlePreviewsCopyWith<_i3.ArticlePreviews>);

  @override
  _i3.ArticlePreviews asCached() =>
      (super.noSuchMethod(
            Invocation.method(#asCached, []),
            returnValue: _FakeArticlePreviews_1(
              this,
              Invocation.method(#asCached, []),
            ),
            returnValueForMissingStub: _FakeArticlePreviews_1(
              this,
              Invocation.method(#asCached, []),
            ),
          )
          as _i3.ArticlePreviews);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
