name: article_browser
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: "3.29.2"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 10.0.1
  bloc_concurrency: 0.3.0
  cherrypick: 2.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  freezed_annotation: 3.0.0
  http: 1.3.0
  json_annotation: 4.9.0
  retrofit: 4.4.2
  retrofit_generator: 9.1.9
  shared_preferences: 2.5.2
  talker: 4.7.1
  bloc_test: 10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 5.0.0
  auto_route_generator: 10.0.1
  build_runner: 2.4.15
  freezed: 3.0.4
  json_serializable: 6.9.4
  mockito: 5.4.5
  test: 1.25.15

flutter:
  uses-material-design: true
