name: Flutter

on:
  push:
    branches: ["main"]

jobs:
  flutter_job:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none
      - name: Analyze code
        run: flutter analyze
      - name: Run unit tests
        run: flutter test
      - name: Build apk
        run: flutter build apk
